config/routes.rb
# frozen_string_literal: true

RainbowStride::Engine.routes.draw do
  resources :workout_plan_exercises, only: %i[update destroy]
  resources :workout_plans
  resources :levels
  resources :exercises
  resources :measurements
  get :generate_svg, to: 'home#generate_svg'
  resources :workouts, only: %i[index show new create] do
    get 'progress', on: :collection
    resources :exercise_logs, only: %i[create update]
    member do
      get ':id/finish', to: 'workouts#finish', as: 'finish'
    end
  end
end

app/models/concerns/rainbow_stride/user_concern.rb
module RainbowStride
  module UserConcern
    extend ActiveSupport::Concern

    included do
      has_many :exercises
    end
  end
end

app/models/rainbow_stride/application_record.rb
module RainbowStride
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/rainbow_stride/exercise.rb
module RainbowStride
  class Exercise < ApplicationRecord
    belongs_to :user
    has_many :exercise_levels, class_name: "RainbowStride::ExerciseLevel", dependent: :destroy, foreign_key: :rainbow_stride_exercise_id
    has_many :workout_plan_exercises, class_name: "RainbowStride::WorkoutPlanExercise", dependent: :destroy
    has_many :workout_plans, class_name: "RainbowStride::WorkoutPlan", through: :exercise_plan
    has_many :exercise_logs, class_name: "RainbowStride::ExerciseLog"

    belongs_to :level, class_name: "RainbowStride::Level", foreign_key: :rainbow_stride_level_id
    belongs_to :junior_description, -> { exercise_levels.where(levels: {name: "Початківець"}) }, class_name: 'RainbowStride::Exercise', optional: true
  end
end

app/models/rainbow_stride/exercise_level.rb
module RainbowStride
  class ExerciseLevel < ApplicationRecord
    belongs_to :level, :class_name => 'RainbowStride::Level', foreign_key: :rainbow_stride_level_id
    belongs_to :exercise, :class_name => 'RainbowStride::Exercise', foreign_key: :rainbow_stride_exercise_id
  end
end

app/models/rainbow_stride/exercise_log.rb
module RainbowStride
  class ExerciseLog < ApplicationRecord
    belongs_to :workout, class_name: "RainbowStride::Workout", foreign_key: :rainbow_stride_workout_id
    belongs_to :exercise, class_name: "RainbowStride::Exercise", foreign_key: :rainbow_stride_exercise_id
  end
end

app/models/rainbow_stride/level.rb
module RainbowStride
  class Level < ApplicationRecord
    # has_many :exercise_levels, class_name: "RainbowStride::ExerciseLevel", dependent: :destroy, foreign_key: :rainbow_stride_level_id
    has_many :exercises, class_name: "RainbowStride::Exercise", foreign_key: :rainbow_stride_level_id
  end
end

app/models/rainbow_stride/measurement.rb
# frozen_string_literal: true

module RainbowStride
  class Measurement < ApplicationRecord
    belongs_to :user, class_name: 'RainbowGate::User', foreign_key: :user_id

    belongs_to :measurement_type, class_name: 'RainbowStride::MeasurementType', foreign_key: :rainbow_stride_measurement_type_id
  end
end

app/models/rainbow_stride/measurement_type.rb
module RainbowStride
  class MeasurementType < ApplicationRecord
    has_many :measurements, class_name: 'RainbowStride::Measurement', foreign_key: :rainbow_stride_measurement_type_id

    def to_s
      [name, "(#{unit})"].join('  ')
    end
  end
end

app/models/rainbow_stride/rainbow_stride/measurement_type.rb
module RainbowStride
  class RainbowStride::MeasurementType < ApplicationRecord
  end
end

app/models/rainbow_stride/user_extension.rb
module RainbowStride
  module UserExtension
    extend ActiveSupport::Concern

    included do
      has_many :measurements, class_name: "RainbowStride::Measurement", foreign_key: :user_id
      has_many :workouts, class_name: "RainbowStride::Workout"
      has_many :exercises, class_name: "RainbowStride::Exercise"
      has_many :exercise_logs, :class_name => 'RainbowStride::ExerciseLog', through: :workouts
      has_many :workout_plans, :class_name => 'RainbowStride::WorkoutPlan', foreign_key: :user_id
    end
  end
end

app/models/rainbow_stride/workout.rb
module RainbowStride
  class Workout < ApplicationRecord
    belongs_to :user
    belongs_to :workout_plan, class_name: "RainbowStride::WorkoutPlan", foreign_key: :rainbow_stride_plan_id
    has_many :exercise_logs, class_name: "RainbowStride::ExerciseLog", foreign_key: :rainbow_stride_workout_id
  end
end

app/models/rainbow_stride/workout_plan.rb
module RainbowStride
  class WorkoutPlan < ApplicationRecord
    belongs_to :user
    has_many :workout_plan_exercises, dependent: :destroy, class_name: "RainbowStride::WorkoutPlanExercise"
    has_many :exercises, through: :workout_plan_exercises, class_name: "RainbowStride::Exercise"
    has_many :workouts, :class_name => 'RainbowStride::Workout', foreign_key: :rainbow_stride_plan_id
    belongs_to :level, class_name: "RainbowStride::Level"
  end
end

app/models/rainbow_stride/workout_plan_exercise.rb
# frozen_string_literal: true

module RainbowStride
  class WorkoutPlanExercise < ApplicationRecord
    belongs_to :exercise, class_name: 'RainbowStride::Exercise'
    belongs_to :workout_plan, class_name: 'RainbowStride::WorkoutPlan'
  end
end

app/controllers/rainbow_stride/application_controller.rb
module RainbowStride
  class ApplicationController < ::ApplicationController
    before_action :authenticate_user!
  end
end

app/controllers/rainbow_stride/exercise_logs_controller.rb
module RainbowStride
  class ExerciseLogsController < ApplicationController
    def create
      @exercise_log = ExerciseLog.new(exercise_log_params)
      @exercise_log.rainbow_stride_workout_id = params[:workout_id]
      @workout = Workout.find(params[:workout_id])

      if @exercise_log.save
        redirect_to workout_path(@workout), notice: 'Exercise log created successfully.'
      else
        redirect_to workout_path(@workout), alert: @exercise_log.errors.full_messages.join(', ')
      end
    end

    def update
      @exercise_log = ExerciseLog.find(params[:id])
      @workout = Workout.find(params[:workout_id])

      if @exercise_log.update(exercise_log_params)
        redirect_to workout_path(@workout), notice: 'Exercise log updated successfully.'
      else
        redirect_to workout_path(@workout), alert: @exercise_log.errors.full_messages.join(', ')
      end
    end

    private

    def exercise_log_params
      params.require(:exercise_log).permit(:rainbow_stride_exercise_id, :weight, :repetitions, :rest_time, :exercise_time)
    end
  end
end

app/controllers/rainbow_stride/exercises_controller.rb
module RainbowStride
  class ExercisesController < ApplicationController
    before_action :set_exercise, only: %i[ show edit update destroy ]

    # GET /exercises
    def index
      @exercises = Exercise.all
    end

    # GET /exercises/1
    def show
    end

    # GET /exercises/new
    def new
      @exercise = Exercise.new
    end

    # GET /exercises/1/edit
    def edit
    end

    # POST /exercises
    def create
      @exercise = Exercise.new(exercise_params)

      if @exercise.save
        redirect_to @exercise, notice: "Exercise was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /exercises/1
    def update
      if @exercise.update(exercise_params)
        redirect_to @exercise, notice: "Exercise was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /exercises/1
    def destroy
      @exercise.destroy
      redirect_to exercises_url, notice: "Exercise was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_exercise
        @exercise = Exercise.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def exercise_params
        params.require(:exercise).permit(:name, :rainbow_stride_level_id)
      end
  end
end

app/controllers/rainbow_stride/home_controller.rb
# app/controllers/rainbow_controller.rb
module RainbowStride
  class HomeController < ApplicationController
    def generate_svg
      @user_data = params[:user_data]
      @measurements = current_user.measurements.order("created_at DESC").group_by(&:measurement_type)
    end
  end

end

app/controllers/rainbow_stride/levels_controller.rb
module RainbowStride
  class LevelsController < ApplicationController
    before_action :set_level, only: %i[ show edit update destroy ]

    # GET /levels
    def index
      @levels = Level.all
    end

    # GET /levels/1
    def show
    end

    # GET /levels/new
    def new
      @level = Level.new
    end

    # GET /levels/1/edit
    def edit
    end

    # POST /levels
    def create
      @level = Level.new(level_params)

      if @level.save
        redirect_to @level, notice: "Level was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /levels/1
    def update
      if @level.update(level_params)
        redirect_to @level, notice: "Level was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /levels/1
    def destroy
      @level.destroy
      redirect_to levels_url, notice: "Level was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_level
        @level = Level.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def level_params
        params.require(:level).permit(:name)
      end
  end
end

app/controllers/rainbow_stride/measurements_controller.rb
# frozen_string_literal: true

module RainbowStride
  class MeasurementsController < ApplicationController
    before_action :set_measurement, only: %i[show edit update destroy]

    def index
      @measurements = current_user.measurements
      @measurement = Measurement.new
      @charts_data = {}
      @measurements.order('created_at DESC').group_by(&:measurement_type).each do |type, measurements|
        data = measurements.group_by { |m| m.date.to_date }.transform_values do |values|
          values.map(&:value).sum.to_f / values.size
        end
        @charts_data[type.name] = data
      end
    end

    def show; end

    def new
      @measurement = RainbowStride::Measurement.new
    end

    def create
      @measurement = Measurement.new(measurement_params)
      @measurement.user = current_user

      if @measurement.save
        redirect_to measurements_path, anchor: sanitize_id(@measurement.measurement_type.name), notice: 'RainbowStride::Measurement was successfully created.'
      else
        render :new, notice: @measurement.errors.full_messages
      end
    end

    def edit; end

    def update
      if @measurement.update(measurement_params)
        redirect_to @measurement, notice: 'RainbowStride::Measurement was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @measurement.destroy
      redirect_to measurements_url, notice: 'RainbowStride::Measurement was successfully destroyed.'
    end

    private

    def sanitize_id(id)
      id.downcase.gsub(/\s+/, '-')
    end

    def set_measurement
      @measurement = RainbowStride::Measurement.find(params[:id])
    end

    def measurement_params
      params.require(:measurement).permit(:rainbow_stride_measurement_type_id, :value, :date)
    end
  end
end

app/controllers/rainbow_stride/workout_plan_exercises_controller.rb
module RainbowStride
  class WorkoutPlanExercisesController < ApplicationController
    def update
      wpe = WorkoutPlanExercise.find(params[:id])
      if wpe.update(workout_plan_exercise_params)
        redirect_to workout_plan_path(wpe.workout_plan)
      else
        head :no_content
      end
    end

    private

    def workout_plan_exercise_params
      params.require(:workout_plan_exercise).permit(:repetitions, :rounds, :weight)
    end
  end
end

app/views/rainbow_stride/plans/_form.html.erb
<%= form_with(model: plan, local: true, html: { class: 'needs-validation', novalidate: true }) do |form| %>
  <% if plan.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
        <% plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :duration %>
    <%= form.datetime_field :duration, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag :selected_exercises, "Selected Exercises" %>
    <ul id="selected-exercises" class="list-group">
    </ul>
  </div>

  <div class="form-group">
    <%= label_tag :level_id, "Level" %>
    <%= select_tag 'level_id', options_from_collection_for_select(RainbowStride::Level.all, :id, :name, { include_blank: 'Please select an level' }), { class: 'form-control', id: 'level-select', name: nil } %>
  </div>

  <div class="form-group" id="exercises-container">
    <% RainbowStride::Level.all.each do |level| %>
      <% level.exercises.each do |exercise| %>
        <div class="form-check" data-level-id="<%= level.id %>">
          <%= form.check_box :exercise_ids, {multiple: true, class: 'form-check-input'}, exercise.id, nil %>
          <%= form.label "exercise_ids_#{exercise.id}", exercise.name, class: 'form-check-label' %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const exercisesContainer = document.getElementById('exercises-container');
        const exercisesChecks = exercisesContainer.querySelectorAll(".form-check");
        const selectedExercises = document.getElementById('selected-exercises');
        const levelSelect = document.getElementById('level-select');
        const selectedExerciseIds = <%= @plan.exercise_ids.present? ? @plan.exercise_ids.to_json.html_safe : '[]' %>;

        exercisesChecks.forEach(ele => ele.style.display = "none");

        if (selectedExerciseIds.length) {
            selectedExerciseIds.forEach(id => {
                const input = document.getElementById(`plan_exercise_ids_${id}`);
                if (input) {
                    input.checked = true;
                    const exerciseCheckbox = document.getElementById(`plan_exercise_ids_${id}`);
                    const levelId = exerciseCheckbox.closest('.form-check').dataset.levelId;
                    const levelLabel = document.querySelector(`#level-select option[value="${levelId}"]`).textContent;
                    addExerciseToList(id, exerciseCheckbox.nextElementSibling.textContent, levelLabel);
                }
            });
        }

        levelSelect.addEventListener('change', function() {
            const selectedLevelId = this.value;
            exercisesChecks.forEach(ele => ele.style.display = "none");
            const filteredExercises = exercisesContainer.querySelectorAll('.form-check[data-level-id="' + selectedLevelId + '"]');
            filteredExercises.forEach(ele => ele.style.display = "block");
        });

        exercisesContainer.addEventListener('change', (e) => {
            if (e.target.tagName === 'INPUT') {
                const exerciseId = e.target.value;
                const exerciseLabel = document.querySelector(`label[for="${e.target.id}"]`).textContent;
                const levelId = event.target.closest('.form-check').dataset.levelId;
                const levelLabel = document.querySelector(`#level-select option[value="${levelId}"]`).textContent;

                if (e.target.checked) {
                    addExerciseToList(exerciseId, exerciseLabel, levelLabel);
                } else {
                    const listItem = selectedExercises.querySelector(`[data-exercise-id="${exerciseId}"]`);
                    selectedExercises.removeChild(listItem);
                }
            }
        });

        function addExerciseToList(exerciseId, exerciseLabel, levelLabel) {
            const listItem = document.createElement('li');
            listItem.classList.add('list-group-item');
            listItem.dataset.exerciseId = exerciseId;
            listItem.textContent = `${exerciseLabel} (${levelLabel})`;
            selectedExercises.appendChild(listItem);
        }
    });
</script>

app/views/rainbow_stride/plans/_plan.html.erb
<div id="<%= dom_id plan %>" class="card mb-3">
  <div class="card-header">
    <strong>Title:</strong>
    <%= plan.title %>
  </div>
  <div class="card-body">
    <p class="card-text">
      <strong>Duration:</strong>
      <%= plan.duration %>
    </p>

    <% end_date = plan.duration %>
    <p class="card-text">
      <strong>End Date:</strong>
      <%= end_date.to_s(:long) %> (in <%= distance_of_time_in_words(Time.current, end_date) %>)
    </p>
  </div>
</div>

app/views/rainbow_stride/plans/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col">
      <h1>New Plan</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= render "form", plan: @plan %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">
      <%= link_to "Back to plans", plans_path, class: "btn btn-outline-secondary" %>
    </div>
  </div>
</div>

app/views/rainbow_stride/plans/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col">
      <h1>Plan</h1>
      <p class="text-success"><%= notice %></p>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= render @plan %>
    </div>
  </div>

  <!-- Display exercises and levels -->
  <div class="row mt-4">
    <div class="col">
      <h2>Exercises</h2>
      <ul class="list-group">
        <% @plan.exercises.order(:name).each do |exercise| %>
          <li class="list-group-item">
            <%= exercise.name %> (<%= exercise.level&.name %>)
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="my-4"></div>
  <h2>Workouts for <%= @plan.title %></h2>

  <% if @workouts.present? %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Start Time</th>
        <th scope="col">End Time</th>
        <th scope="col">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @workouts.each do |workout| %>
        <tr>
          <td><%= workout.id %></td>
          <td><%= workout.start_time %></td>
          <td><%= workout.end_time %></td>
          <td>
            <%= link_to 'Show', workout_path(workout), class: 'btn btn-primary btn-sm me-1' %>
            <%#= link_to 'Edit', edit_workout_path(workout), class: 'btn btn-secondary btn-sm me-1' %>
            <%= link_to 'Destroy', workout_path(workout), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="alert alert-warning" role="alert">
      No workouts found for this blueprint.
    </div>
  <% end %>


  <div class="row mt-4">
    <div class="col">
      <h2>Exercise Progress</h2>
      <% @workout_exercise_logs.each do |exercise, data| %>
        <h4><%= exercise %></h4>
        <%= line_chart [
                         {name: "Weight", data: data[:weights]},
                         {name: "Repetitions", data: data[:repetitions]}
                       ],
                       colors: ['#b00', '#00b'],
                       dataset: { borderWidth: 2 },
                       library: { scales: { y: { beginAtZero: true } } }
        %>
      <% end %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">
      <%= link_to "Edit this plan", edit_plan_path(@plan), class: "btn btn-outline-primary mr-2" %>
      <%= link_to "Back to plans", plans_path, class: "btn btn-outline-secondary mr-2" %>
      <%= button_to "Destroy this plan", @plan, method: :delete, class: "btn btn-outline-danger", data: { confirm: "Are you sure you want to delete this plan?" } %>
    </div>
  </div>
</div>