config/routes.rb
# frozen_string_literal: true

RainbowStride::Engine.routes.draw do
  resources :workout_plan_exercises, only: %i[update destroy]
  resources :workout_plans
  resources :levels
  resources :exercises
  resources :measurements
  get :generate_svg, to: 'home#generate_svg'
  resources :workouts, only: %i[index show new create] do
    get 'progress', on: :collection
    resources :exercise_logs, only: %i[create update]
    member do
      get ':id/finish', to: 'workouts#finish', as: 'finish'
    end
  end
end

app/models/concerns/rainbow_stride/user_concern.rb
module RainbowStride
  module UserConcern
    extend ActiveSupport::Concern

    included do
      has_many :exercises
    end
  end
end

app/models/rainbow_stride/application_record.rb
module RainbowStride
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/rainbow_stride/exercise.rb
module RainbowStride
  class Exercise < ApplicationRecord
    belongs_to :user
    has_many :exercise_levels, class_name: "RainbowStride::ExerciseLevel", dependent: :destroy, foreign_key: :rainbow_stride_exercise_id
    has_many :workout_plan_exercises, class_name: "RainbowStride::WorkoutPlanExercise", dependent: :destroy
    has_many :workout_plans, class_name: "RainbowStride::WorkoutPlan", through: :exercise_plan
    has_many :exercise_logs, class_name: "RainbowStride::ExerciseLog"

    belongs_to :level, class_name: "RainbowStride::Level", foreign_key: :rainbow_stride_level_id
    belongs_to :junior_description, -> { exercise_levels.where(levels: {name: "Початківець"}) }, class_name: 'RainbowStride::Exercise', optional: true
  end
end

app/models/rainbow_stride/exercise_level.rb
module RainbowStride
  class ExerciseLevel < ApplicationRecord
    belongs_to :level, :class_name => 'RainbowStride::Level', foreign_key: :rainbow_stride_level_id
    belongs_to :exercise, :class_name => 'RainbowStride::Exercise', foreign_key: :rainbow_stride_exercise_id
  end
end

app/models/rainbow_stride/exercise_log.rb
module RainbowStride
  class ExerciseLog < ApplicationRecord
    belongs_to :workout, class_name: "RainbowStride::Workout", foreign_key: :rainbow_stride_workout_id
    belongs_to :exercise, class_name: "RainbowStride::Exercise", foreign_key: :rainbow_stride_exercise_id
  end
end

app/models/rainbow_stride/level.rb
module RainbowStride
  class Level < ApplicationRecord
    # has_many :exercise_levels, class_name: "RainbowStride::ExerciseLevel", dependent: :destroy, foreign_key: :rainbow_stride_level_id
    has_many :exercises, class_name: "RainbowStride::Exercise", foreign_key: :rainbow_stride_level_id
  end
end

app/models/rainbow_stride/measurement.rb
# frozen_string_literal: true

module RainbowStride
  class Measurement < ApplicationRecord
    belongs_to :user, class_name: 'RainbowGate::User', foreign_key: :user_id

    belongs_to :measurement_type, class_name: 'RainbowStride::MeasurementType', foreign_key: :rainbow_stride_measurement_type_id
  end
end

app/models/rainbow_stride/measurement_type.rb
module RainbowStride
  class MeasurementType < ApplicationRecord
    has_many :measurements, class_name: 'RainbowStride::Measurement', foreign_key: :rainbow_stride_measurement_type_id

    def to_s
      [name, "(#{unit})"].join('  ')
    end
  end
end

app/models/rainbow_stride/rainbow_stride/measurement_type.rb
module RainbowStride
  class RainbowStride::MeasurementType < ApplicationRecord
  end
end

app/models/rainbow_stride/user_extension.rb
module RainbowStride
  module UserExtension
    extend ActiveSupport::Concern

    included do
      has_many :measurements, class_name: "RainbowStride::Measurement", foreign_key: :user_id
      has_many :workouts, class_name: "RainbowStride::Workout"
      has_many :exercises, class_name: "RainbowStride::Exercise"
      has_many :exercise_logs, :class_name => 'RainbowStride::ExerciseLog', through: :workouts
      has_many :workout_plans, :class_name => 'RainbowStride::WorkoutPlan', foreign_key: :user_id
    end
  end
end

app/models/rainbow_stride/workout.rb
module RainbowStride
  class Workout < ApplicationRecord
    belongs_to :user
    belongs_to :workout_plan, class_name: "RainbowStride::WorkoutPlan", foreign_key: :rainbow_stride_plan_id
    has_many :exercise_logs, class_name: "RainbowStride::ExerciseLog", foreign_key: :rainbow_stride_workout_id
  end
end

app/models/rainbow_stride/workout_plan.rb
module RainbowStride
  class WorkoutPlan < ApplicationRecord
    belongs_to :user
    has_many :workout_plan_exercises, dependent: :destroy, class_name: "RainbowStride::WorkoutPlanExercise"
    has_many :exercises, through: :workout_plan_exercises, class_name: "RainbowStride::Exercise"
    has_many :workouts, :class_name => 'RainbowStride::Workout', foreign_key: :rainbow_stride_plan_id
    belongs_to :level, class_name: "RainbowStride::Level"
  end
end

app/models/rainbow_stride/workout_plan_exercise.rb
# frozen_string_literal: true

module RainbowStride
  class WorkoutPlanExercise < ApplicationRecord
    belongs_to :exercise, class_name: 'RainbowStride::Exercise'
    belongs_to :workout_plan, class_name: 'RainbowStride::WorkoutPlan'
  end
end

app/controllers/rainbow_stride/application_controller.rb
module RainbowStride
  class ApplicationController < ::ApplicationController
    before_action :authenticate_user!
  end
end

app/controllers/rainbow_stride/exercise_logs_controller.rb
module RainbowStride
  class ExerciseLogsController < ApplicationController
    def create
      @exercise_log = ExerciseLog.new(exercise_log_params)
      @exercise_log.rainbow_stride_workout_id = params[:workout_id]
      @workout = Workout.find(params[:workout_id])

      if @exercise_log.save
        redirect_to workout_path(@workout), notice: 'Exercise log created successfully.'
      else
        redirect_to workout_path(@workout), alert: @exercise_log.errors.full_messages.join(', ')
      end
    end

    def update
      @exercise_log = ExerciseLog.find(params[:id])
      @workout = Workout.find(params[:workout_id])

      if @exercise_log.update(exercise_log_params)
        redirect_to workout_path(@workout), notice: 'Exercise log updated successfully.'
      else
        redirect_to workout_path(@workout), alert: @exercise_log.errors.full_messages.join(', ')
      end
    end

    private

    def exercise_log_params
      params.require(:exercise_log).permit(:rainbow_stride_exercise_id, :weight, :repetitions, :rest_time, :exercise_time)
    end
  end
end

app/controllers/rainbow_stride/exercises_controller.rb
module RainbowStride
  class ExercisesController < ApplicationController
    before_action :set_exercise, only: %i[ show edit update destroy ]

    # GET /exercises
    def index
      @exercises = Exercise.all
    end

    # GET /exercises/1
    def show
    end

    # GET /exercises/new
    def new
      @exercise = Exercise.new
    end

    # GET /exercises/1/edit
    def edit
    end

    # POST /exercises
    def create
      @exercise = Exercise.new(exercise_params)

      if @exercise.save
        redirect_to @exercise, notice: "Exercise was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /exercises/1
    def update
      if @exercise.update(exercise_params)
        redirect_to @exercise, notice: "Exercise was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /exercises/1
    def destroy
      @exercise.destroy
      redirect_to exercises_url, notice: "Exercise was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_exercise
        @exercise = Exercise.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def exercise_params
        params.require(:exercise).permit(:name, :rainbow_stride_level_id)
      end
  end
end

app/controllers/rainbow_stride/home_controller.rb
# app/controllers/rainbow_controller.rb
module RainbowStride
  class HomeController < ApplicationController
    def generate_svg
      @user_data = params[:user_data]
      @measurements = current_user.measurements.order("created_at DESC").group_by(&:measurement_type)
    end
  end

end

app/controllers/rainbow_stride/levels_controller.rb
module RainbowStride
  class LevelsController < ApplicationController
    before_action :set_level, only: %i[ show edit update destroy ]

    # GET /levels
    def index
      @levels = Level.all
    end

    # GET /levels/1
    def show
    end

    # GET /levels/new
    def new
      @level = Level.new
    end

    # GET /levels/1/edit
    def edit
    end

    # POST /levels
    def create
      @level = Level.new(level_params)

      if @level.save
        redirect_to @level, notice: "Level was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /levels/1
    def update
      if @level.update(level_params)
        redirect_to @level, notice: "Level was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /levels/1
    def destroy
      @level.destroy
      redirect_to levels_url, notice: "Level was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_level
        @level = Level.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def level_params
        params.require(:level).permit(:name)
      end
  end
end

app/controllers/rainbow_stride/measurements_controller.rb
# frozen_string_literal: true

module RainbowStride
  class MeasurementsController < ApplicationController
    before_action :set_measurement, only: %i[show edit update destroy]

    def index
      @measurements = current_user.measurements
      @measurement = Measurement.new
      @charts_data = {}
      @measurements.order('created_at DESC').group_by(&:measurement_type).each do |type, measurements|
        data = measurements.group_by { |m| m.date.to_date }.transform_values do |values|
          values.map(&:value).sum.to_f / values.size
        end
        @charts_data[type.name] = data
      end
    end

    def show; end

    def new
      @measurement = RainbowStride::Measurement.new
    end

    def create
      @measurement = Measurement.new(measurement_params)
      @measurement.user = current_user

      if @measurement.save
        redirect_to measurements_path, anchor: sanitize_id(@measurement.measurement_type.name), notice: 'RainbowStride::Measurement was successfully created.'
      else
        render :new, notice: @measurement.errors.full_messages
      end
    end

    def edit; end

    def update
      if @measurement.update(measurement_params)
        redirect_to @measurement, notice: 'RainbowStride::Measurement was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @measurement.destroy
      redirect_to measurements_url, notice: 'RainbowStride::Measurement was successfully destroyed.'
    end

    private

    def sanitize_id(id)
      id.downcase.gsub(/\s+/, '-')
    end

    def set_measurement
      @measurement = RainbowStride::Measurement.find(params[:id])
    end

    def measurement_params
      params.require(:measurement).permit(:rainbow_stride_measurement_type_id, :value, :date)
    end
  end
end

app/controllers/rainbow_stride/workout_plan_exercises_controller.rb
module RainbowStride
  class WorkoutPlanExercisesController < ApplicationController
    def update
      wpe = WorkoutPlanExercise.find(params[:id])
      if wpe.update(workout_plan_exercise_params)
        redirect_to workout_plan_path(wpe.workout_plan)
      else
        head :no_content
      end
    end

    private

    def workout_plan_exercise_params
      params.require(:workout_plan_exercise).permit(:repetitions, :rounds, :weight)
    end
  end
end

app/views/rainbow_stride/exercises/_exercise.html.erb
<div class="container py-4">
  <div class="row">
    <div class="col-md-12 text-center mb-4">
      <h1><%= exercise.name %></h1>
    </div>
  </div>
  <div id="<%= dom_id exercise %>" class="row justify-content-center">
    <div class="col-md-6">
      <table class="table table-bordered table-striped">
        <tbody>
        <tr>
          <th>Name:</th>
          <td><%= exercise.name %></td>
        </tr>
        <tr>
          <th>User:</th>
          <td><%= exercise.user.to_s %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
  <% exercise.exercise_levels.each do |level| %>
    <div class="row mt-4">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <%= level.level.name %>
          </div>
          <div class="card-body">
            <h5 class="card-title">Description:</h5>
            <p class="card-text"><%= level.description %></p>
            <h5 class="card-title">How to do:</h5>
            <p class="card-text"><%= level.how_to_do %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/rainbow_stride/exercises/_form.html.erb
<%= form_with(model: exercise, local: true, html: { class: 'needs-validation p-3', novalidate: true }) do |form| %>
  <% if exercise.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
        <% exercise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="d-flex justify-content-center">
    <div class="col-md-6">
      <div class="row mb-4">
        <div class="col-md-12">
          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="col-md-12">
          <div class="form-group">
            <%= form.label :level_id, "Level" %>
            <%= form.collection_select :rainbow_stride_level_id, RainbowStride::Level.all, :id, :name, { prompt: 'Select Level' }, { class: 'form-control' } %>
          </div>
        </div>
      </div>

      <div class="form-group d-flex justify-content-end">
        <%= form.submit class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/rainbow_stride/exercises/edit.html.erb
<div class="container py-4">
  <div class="row">
    <div class="col-md-12 text-center mb-4">
      <h1>Editing exercise</h1>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="border shadow p-3">
        <%= render "form", exercise: @exercise %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center mt-3">
      <%= link_to "Show this exercise", @exercise, class: 'btn btn-info' %> |
      <%= link_to "Back to exercises", exercises_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/rainbow_stride/exercises/index.html.haml
.container
  %h1 Rainbow Stride Exercises

  .table-responsive
    %table.table.table-striped
      %thead
        %tr
          %th Name
          %th Created At
          %th Updated At
          %th Actions
      %tbody
        - @exercises.each do |exercise|
          %tr
            %td= exercise.name
            %td= exercise.created_at
            %td= exercise.updated_at
            %td
              = link_to 'Show', exercise_path(exercise), class: 'btn btn-primary btn-sm'
              = link_to 'Edit', edit_exercise_path(exercise), class: 'btn btn-secondary btn-sm'
              = link_to 'Delete', exercise_path(exercise), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'

  = link_to 'New Exercise', new_exercise_path, class: 'btn btn-success'

app/views/rainbow_stride/exercises/new.html.erb
<div class="container py-4">
  <div class="row">
    <div class="col-md-12 text-center mb-4">
      <h1>New exercise</h1>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="border shadow p-3">
        <%= render 'form', exercise: @exercise %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center mt-3">
      <%= link_to "Back to exercises", exercises_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/rainbow_stride/exercises/show.html.erb
<div class="container py-4">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <%= render @exercise %>

  <div class="row mt-4 mb-2">
    <div class="col-md-12 text-center">
      <%= link_to "Edit this exercise", edit_exercise_path(@exercise), class: 'btn btn-warning me-3 mb-2' %> |
      <%= link_to "Back to exercises", exercises_path, class: 'btn btn-secondary ms-3 mb-2' %>

      <%= button_to "Destroy this exercise", @exercise, method: :delete, class: 'btn btn-danger ms-3' %>
    </div>
  </div>
</div>